### PR TITLE
Added typings.json for typings tool support

### PR DESCRIPTION
**Pull request by jcristovao**
Hey!

Typings is a very handy tool to install and manage typescript definitions.
https://github.com/typings/typings

I still did not had the time to figure out our their [Typings Registry](https://github.com/typings/registry) works (it does seem to be more principled that the mess which is DefinitelyTyped), but this PR is a start.

With this PR you can do:

typings install --global github:vitaly-t/pg-promise

And it works properly, including all the definition files.

Thanks

### CODE REVIEW

**Comment by vitaly-t** [comment]
I'm gonna do a bit of research on this first, to understand how this really works.

**Comment by vitaly-t** [comment]
@jcristovao I still cannot make it work with a simple path, having this always:
```js
/// <reference path='../typings/globals/pg-promise/pg-promise.d.ts' />
```
Is there another change I need to make to make it pick up the library automatically?

**Comment by jcristovao** [comment]
Did you install with --global and then included the index?

`/// <reference path='../typings/index.d.ts' />`

?

**Comment by vitaly-t** [comment]
I will try later again. In the meantime, it is all included in 4.3.2 - check it out ;)

**Comment by vitaly-t** [comment]
>Did you install with --global and then included the index?

Which index file do you mean?

So far the only way I could include it is via a complete relative path:
```js
/// <reference path='../typings/globals/pg-promise/index' />
```

I must be missing something...

**Comment by vitaly-t** [comment]
I missed the fact that you were including `index`, and not `pg-promise`

Using this minimum actually works! :)

```js
/// <reference path='../typings/index' />
```

**Comment by vitaly-t** [comment]
@jcristovao I have updated the [TypeScript documentation](https://github.com/vitaly-t/pg-promise/tree/master/typescript) ;)

**Pull request merged**
