### PR TITLE
Update Readme.md to note poor stack traces for default ES6 Promises

### PR DESCRIPTION
**Pull request by tonylukasavage**
We can use this as a starting point if this is not satisfactory. Not sure how minimal or descriptive you would like this to be. I can include examples of bad stack traces, but I didn't want to clutter docs much further without your consent.

### CODE REVIEW

**Comment by vitaly-t** [comment]
Well, they all generate poor stack traces, not just ES6 Promise :)

**Comment by tonylukasavage** [comment]
Understood. Would it be simpler to reference the SO answer you have, or add
it's content to the promisdLib section?

**Comment by vitaly-t** [comment]
I've just updated the section: https://github.com/vitaly-t/pg-promise#promiselib

the change:

> Bluebird - best alternative all around, which includes the very important Long Stack Traces;

Perhaps should suffice? ;)

**Comment by tonylukasavage** [comment]
I mean, sure, that's better than nothing, but you understand that "long"
stack traces aren't the point, right? It's not that the stack traces aren't
long with the default ES6 promises, it's that they are totally not
actionable with the information given for anything but trivial examples. Do
we agree that that's a problem? If not, then we can just close this issue
and I can be happy I found it early.

I'm not "blaming" pg-promise, I'm just noting a problem with the default
behavior that surfaces through it. It's up to you whether you care how that
affects users.

**Comment by vitaly-t** [comment]
> It's up to you whether you care how that affects users.

I did reply to all your questions, and I did an update in documentation, which means that I do care. Beyond that, I'm now too focused on [version 6.x](https://github.com/vitaly-t/pg-promise/tree/6.x) of the library. Legacy documentation isn't a priority for me right now.

**Comment by tonylukasavage** [comment]
Kk, thanks for the doc update, good luck on 6.x

**Pull request closed without merging**
