### PR TITLE
Add "finish" event to notify that a query has been executed

### PR DESCRIPTION
**Pull request by josefzamrzla**

### CODE REVIEW

**Comment by vitaly-t** [comment]
@josefzamrzla Please follow with an explanation of why you think this is needed.

This library already includes event `query`, which let's you know when every query is about to execute, and it has event `receive`, which tells you when you get any data, so effectively whenever a query finishes.

So why would you need a separate `finish` event? Also consider that when any query request resolves, you also get your event finish point.

**Comment by josefzamrzla** [comment]
@vitaly-t  I'd like to have an event like that to be able to track/log all executed queries with their duration and number of fetched/affected rows to help me with query optimizations. I've seen an event 'receive' but this event is triggered only when a query returns some data, it is not triggered for data changing queries without RETURNING clause.

**Comment by josefzamrzla** [comment]
```javascript
options.finish = (stats, e) => {
    let color = stats.duration && stats.duration < 500 ? 'green' : 'red'
    console.log(chalk[color](
        `\n${e.query.replace(/\t/g, '').trim()}\nFetched ${stats.rowCount} rows in: ${stats.duration} ms\n`
    ))
}
```

**Comment by vitaly-t** [comment]
@josefzamrzla Thanks!

I'll have another look at it later in the week. It will require writing tests before it can be submitted.

**Comment by vitaly-t** [comment]
@josefzamrzla this library isn't the best way to approach query performance optimization, you should rely on the internal database performance analysis, using query [EXPLAIN](https://www.postgresql.org/docs/9.5/static/using-explain.html).

**Comment by josefzamrzla** [comment]
@vitaly-t sure, but this event can notify me about all (successfully) finished queries

**Comment by josefzamrzla** [comment]
@vitaly-t to better explain my motivation - I have an app that already uses pg-promise and I want to be able to detect probably non-optimized queries for further investigation. I know that the 'duration' time is not a 'query time' but some kind of 'fetch time' but that's ok in development mode.

**Comment by vitaly-t** [comment]
I understand your reasoning for doing this, but im trying to figure out just how generic this is for anybody else to need it... this is the first time for this kind of request, and i like avoiding bloating the library when possible ;)

**Comment by vitaly-t** [comment]
@josefzamrzla sorry for the delay with decision on this, but I'm still not convinced that anybody else would need this feature. It would only make a tiny helper for diagnosing performance, and not a very good one at that.

**Comment by vitaly-t** [comment]
Closing, for the lack of value to the community. It is more important to keep the code clean than to keep extending it with something of little value.

**Comment by josefzamrzla** [comment]
Ok :-)

**Comment by vitaly-t** [comment]
Re-asked in https://github.com/vitaly-t/pg-promise/issues/283

**Pull request closed without merging**
