### PR TITLE
Add typings entry to package.json

### PR DESCRIPTION
**Pull request by xiamx**
I think this is what @blakeembrey suggested in https://github.com/vitaly-t/pg-promise/pull/232#issuecomment-260197804

### CODE REVIEW

**Comment by blakeembrey** [comment]
Yep, that should be all that's needed.

**Comment by blakeembrey** [comment]
The only thing that would need to be fixed is the dependency (spex) if that is used. If it is also updated to the same format, you'll be able to have everything working in TypeScript for the beginning without any external tools needed.

**Comment by xiamx** [comment]
@blakeembrey how should dependencies on global node definition (https://github.com/vitaly-t/pg-promise/blob/master/typings.json#L11) be handled?

**Comment by blakeembrey** [comment]
You can continue using `typings` for development locally with those. I'm not 100% sure what `spex` does though, but if that can be turned into an external module it'd be good.

**Comment by xiamx** [comment]
Thanks @blakeembrey 

Please don't merge this yet. Once https://github.com/vitaly-t/spex/pull/6 is merged, I'll update this pull-request with changes related to spex

**Comment by vitaly-t** [comment]
@xiamx `spex` has been merged and released as version `1.1`.

Do you need to make some changes here before I accept the merge? (that's what you said above).

**Comment by vitaly-t** [comment]
@xiamx I see the change doesn't build unde Node.js 4, 6 and 7, due to an issue with the TypeScript test:

```
Failures:
  1) Typescript build must build without error
   Message:
     Expected { killed : false, code : 127, signal : null, cmd : 'tsc' } to be null.
   Stacktrace:
     Error: Expected { killed : false, code : 127, signal : null, cmd : 'tsc' } to be null.
    at /home/travis/build/vitaly-t/pg-promise/test/typescriptSpec.js:8:31
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by xiamx** [comment]
Hi @vitaly-t 
I updated this pull request with more changes. Since turning ambient definition into module definition unindents the `d.ts` files by a level, there are a lot of whitespace changes. For your reviewing pleasure, it might better to review them with whitespace changes off (https://github.com/vitaly-t/pg-promise/pull/238/files?w=1)

The general format of the patch is almost the same as https://github.com/vitaly-t/spex/pull/6

1. `typings` key is introduced to `package.json` pointing to `typescript/pg-promise.d.ts`
2. Then applying Blake's suggestion, I turned `typescript/*.d.ts` from ambient definitions to module definitions. This step involves removing module declaration and unindenting the `d.ts` file.
3. I also updated `test/typescript/*` to reflect the changes made in 2.
4. A `typescriptSpec.js` is added so travis can test for the 
5. And finally, update of README to reflect new changes

**Comment by xiamx** [comment]
I forgot to add typescript in as a devdependency, maybe that's why it failed. Looks like everything is building fine now :)

**Comment by vitaly-t** [comment]
@xiamx Thank you! 👍 

We now need to update the following:

https://github.com/vitaly-t/pg-promise/tree/master/typescript

https://github.com/vitaly-t/pg-promise/blob/master/typescript/ext-promise.d.ts

**Pull request merged**
