### PR TITLE
Fix typescript definition for pg-minify reference

### PR DESCRIPTION
**Pull request by sfsr12**
The type exported for minify was incorrect

### CODE REVIEW

**Comment by vitaly-t** [comment]
Incorrect how? Please specify the issue you are having. The rest of the imports are the same, and they work fine.

**Comment by sfsr12** [comment]
Sorry - I should have been more clear - I was working with it so it was obvious to me :)

The way it is exported in pgp it is unable to be used in Typescript.  If you call pgp.minify.default(...) you get:
```
TypeError: __1.pgp.minify.default is not a function
```

If you call pgp.minify(...) you get a type error:
```
This expression is not callable.
  Type 'typeof pgMinify' has no call signatures.
```

Changing the definition as I did in the PR everything works as expected

**Comment by sfsr12** [comment]
I'd be happy to look at the tests that are breaking - but I unfortunately don't know where to even see what is breaking - When I look at the travis-ci link above I see the error is:
 ```
 Typescript build must build without error
 ```
 But I don't know how to see what the build error was.  I am ignorant in regard to this tool - any pointers on how to find the issue would be appreciated.

Thanks

**Comment by vitaly-t** [comment]
* `pgp.minify.default` - there is no such thing in that library
* Calling `pgp.minify('sql...')` works perfectly for me

I just tested all this with the latest version, and I do not see any issue.

Are you using the latest version of the library?

Maybe you are using some import-breaking TS config option?

**Comment by sfsr12** [comment]
Strange... I will try to make a small repo project and maybe while I make that I will see what my issue is.

**Comment by sfsr12** [comment]
I can try to make a repo project if you would like to see it in a project - but even on the simple Typescript playground the issue shows up.

[Typescript Playground Example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBGA5gBShEwDOBTOAzNEOAciQFoxCttiBuAWACgBjCAO03gEcBXbKAJ5wAvCQDKAUQAyEgMIAVOAHcAFgEMY2AG784AMQBKAeQCyylf2386TVh3ibOARhEIUVHADoMbYHgEAFLz8AgCUtHAA9JFw8gJguAAm2HjAvjDA7JhwmGpCMCpYcFhsxPDMagA2lWoARpXYtlkO2JwATK5IqOjU3ml+Ap7JeGo8lTBBfIKhUTHyhdlgapg42TDx2GTMFswA1mmIcGRwtTzwELVamTyYlUIlZXBqcAUHQA)

**Comment by vitaly-t** [comment]
That usage does look unusual...

Are you trying to build this for the client-side? 😄 

Here's my configuration:

```json
  "compilerOptions": {
    "module": "commonjs",
    "sourceMap": true,
    "strict": true,
    "experimentalDecorators": true,
    "target": "ES2017"
  }
```

And it all builds just fine.

For one thing, in your config `"moduleResolution": 2` definitely causes problems.

For another - why are you using `minify` directly like this? I mean, it should work and all, but still, I don't get it why would you want it outside of `QueryFile`-s.

**Comment by vitaly-t** [comment]
Also, I think you can just do `import * as pgMinify from 'pg-minify'`

**Comment by sfsr12** [comment]
OK - so I have looked into it more and found the disconnect.

My config uses `"esModuleInterop": true`

This is the current default by typescript (ie: tsc --init) setting

It resolves issues around the out of spec usage of `import * as foo`

See more here: https://stackoverflow.com/questions/56238356/understanding-esmoduleinterop-in-tsconfig-file

That at least answers the question as to "why" we are seeing different behavior - and I will leave it up to you to decide for your project which is the "correct" behavior.

**Comment by sfsr12** [comment]
To clarify my concerns above - pgPromise.pg is not impacted.  Maybe because it exports `declare namespace pg ` instead of a single function as pg-minify does?  I'm really not well versed enough in the specifics of this to know "why" pg-subset works and pg-minify does not.  That is just a guess

**Comment by vitaly-t** [comment]
I think at this point we are just gonna leave it, because we have nothing conclusive here to warrant a change.

**Comment by vitaly-t** [comment]
Closing, because the issue is without conclusion, so no PR needed.

**Pull request closed without merging**
