### PR TITLE
Enable Github Action

### PR DESCRIPTION
**Pull request by dplewis**
This pull request enables GitHub Actions to run CI. This PR requires a password on the postgres test database. 

### TODO
- [x] Test Windows Locally (I ran it on a Mac and Github CI runs on Ubuntu)
- [ ] Contributor's Guide (Separate PR)

@vitaly-t Let me know if you have any questions

### CODE REVIEW

**Comment by dplewis** [comment]
@vitaly-t This is ready for review

**Comment by vitaly-t** [comment]
LGTM, and local tests on Windows still run well.

**Comment by vitaly-t** [comment]
Thanks! Merged ;)

**Comment by dplewis** [comment]
I think you should change your merge settings to `squash and merge`. Your commit history will be cluttered.

**Comment by vitaly-t** [comment]
@dplewis 

That option is already set ON. What else do I need to do then?

image

**Comment by dplewis** [comment]
I think if you hit the arrow and do it once, github will remember it

Screen Shot 2022-12-30 at 3 38 31 PM

**Comment by vitaly-t** [comment]
Got it! I will try to remember that for the next PR :smile:

**Comment by vitaly-t** [comment]
@dplewis You are the CI expert who integrated it. Any idea why it started failing recently? Local tests all pass without issues.

**Pull request merged**
